# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c71ba87ce7f3c30c219ec22fba8f39029006ca1ebfa793165ea6351fcd5f767adc97dbdbf751ffb9085ce18c92fa35774d2586a2ce1a0871d91d3a37a815bdc

test:
  secret_key_base: 5dc1fcb7e156d11fc5b3e5834740f787652aadae42d3b81035eed54373846abf1a6e695b4d94e63a4cc55533a4c8b7c69de1b810be0063d4093258b9393652e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
